[package]
name = "backu/trialscripting"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "sunspringdev/promise@4.0.0"
Animation = "dig1t/animation@1.0.8"
Badge = "dig1t/badge@1.0.8"
Cache = "dig1t/cache@1.0.10"
GamePass = "dig1t/gamepass@1.0.9"
Maid = "dig1t/maid@1.1.3"
Palette = "dig1t/palette@1.0.1"
ProfileDB = "dig1t/profiledb@1.0.10"
Promise = "dig1t/promise@1.1.3"
Ragdoll = "dig1t/ragdoll@1.0.4"
Replica = "dig1t/replica@1.0.15"
Signal = "dig1t/signal@1.0.3"
State = "dig1t/state@1.2.2"
Trash = "dig1t/trash@1.0.4"
Util = "dig1t/util@1.0.20"
CamShake = "developercron/camerashake@0.2.0"